version: '2'
services:
    vhubweb-mongodb:
        image: mongo:3.2.10
        ports:
            - "27017:27017"
        command: mongos --configdb vhubweb-mongodb-config
    vhubweb-mongodb-node:
        build:
            context: .
            dockerfile: mongodb/MongoDB.Dockerfile
        command: mongod --replSet rs1 --noprealloc --smallfiles
    vhubweb-mongodb-config:
        image: mongo:3.2.10
        container_name: vhubweb-mongodb-config
        command: mongod --noprealloc --smallfiles --configsvr --dbpath /data/db
